spring:
  # Mybatis DATABASE CONFIG
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wdog?useUnicode=yes&characterEncoding=UTF8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Power123
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15

mybatis:
  #MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations : classpath*:mybatis/*.xml,classpath*:mybatis/*/*.xml
  #MyBaits 别名包扫描路径，多个package用逗号或者分号分     隔
  typeAliasesPackage: com.theus.health.*.model.po